project:
  type: website
  output-dir: docs

website:
  title: "RNA-seq data analysis workflow"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: episode_1.qmd
        text: Episode 1 - Overview of the workflow  
